### PR TITLE
FAQ: added Device unavailable if it cannot reach NTP server

### PR DESCRIPTION
**Pull request by Heisenberg2980**
Added comment about device being unavailable if it cannot reach NTP server to update time

### CODE REVIEW

**Comment by ascillato** [comment]
Hi, this is not a normal behavior to document as such. This is a bug from the Arduino core that have been fixed twice already but it have come up again. It is reported in Tasmota at https://github.com/arendst/Tasmota/issues/14394

**Comment by Heisenberg2980** [comment]
Actually https://github.com/arendst/Tasmota/issues/14394 seems to be a different issue where the physical buttons stop working when wifi is down (it is not talking about NTP/time).

This problem with NTP servers seems to be affecting a lot of people, and I think it should be documented in the FAQ section so people don´t need to search between hundreds of issues to find the cause and the possible workarounds while a solution for this problem is found.

Wouldn´t be better to add this to the FAQ section indicating the reason, and in case this is fixed at some point the FAQ section is removed?

**Comment by ascillato** [comment]
Yes, you are right. Also, we should add that it is a known bug we are working on to solve.

**Comment by Heisenberg2980** [comment]
@ascillato thanks for the suggestion, I have updated the comment

**Comment by Heisenberg2980** [comment]
@ascillato do you have permissions to merge this PR? if not, do you know who can merge it?

**Pull request merged**
