### PR TITLE
Update Smart-Meter-Interface.md

### PR DESCRIPTION
**Pull request by carsten12**
Added support for Elster F96 Plus (Sharky 775) heat meter

### CODE REVIEW

**Comment by blakadder** [comment]
proper formatting is not followed

**Comment by carsten12** [comment]
Sorry, I don‘t know what you mean, I copied it to look like all other entries, what‘s wrong? Ready to edit it when necessary…

**Comment by blakadder** [comment]
you did not because your doesn't have the proper indentation like all the others

**Comment by carsten12** [comment]
@blakadder sorry, I am a newbie. Hope it is ok now.

**Pull request merged**
