### PR TITLE
Additional example for Rules#Timer

### PR DESCRIPTION
**Pull request by StoyanDimitrov**
Add example clarifying the usage.

### CODE REVIEW

**Comment by blakadder** [comment]
i don't get it... why two identical examples?

**Comment by StoyanDimitrov** [comment]
Because one example is no enough to convey the connection between the two 1's. What exactly those 1's mean? Where they come from? Are they bound to the Rule1? The two examples combined make the connection clearer.

**Comment by barbudor** [comment]
This is breaking the presentation
why not using a generic approach such as
`Rules#Timer=<x>` when countdown `RuleTimer<x>` expires (where `<x>` = `1..8`)

**Comment by StoyanDimitrov** [comment]
Now feels close to the Commands. Thank you fro the suggestion.

**Comment by barbudor** [comment]
Thanks @StoyanDimitrov

**Pull request merged**
