### PR TITLE
Update SML Driver Doc

### PR DESCRIPTION
**Pull request by kugelkopf123**
Added new Meter and explain the method of changing baud rate while operating.

### CODE REVIEW

**Comment by meingraham** [comment]
@gemu2015 

Can you review please? The smart meter interface & scripting is quite complex and I don't want to miss anything that you can certainly catch.

Cheers!

Mike

**Comment by gemu2015** [comment]
@meingraham 
this example looks good and also shows how to calculate daily, monthly and yearly values.

the sml interface is quite complex and surely some more documentation on parameters would be nice.

i don't have spare time at the moment however and even are offline for some weeks in march

**Comment by kugelkopf123** [comment]
Im trying to enhance it more and more. But it’s quite complex so it take some time.

**Comment by meingraham** [comment]
@kugelkopf123 

As you incrementally enhance the documentation, just create new PRs. Thanks for doing this!

**Comment by kugelkopf123** [comment]
@blakadder What is the reason for this revert?

**Comment by blakadder** [comment]
breaking the entire site... please edit just the .md files

**Pull request merged**
