### PR TITLE
Remove GPIO0 and GND wired bridge after flashing

### PR DESCRIPTION
**Pull request by flywire**
Describe the need for bridge removal after flashing. Suggested text provided,

### CODE REVIEW

**Comment by blakadder** [comment]
what is **run mode** ?

**Comment by flywire** [comment]
If there is a `program/flash mode` there must be a mode to describe the other state. Based on my search it seems to be `run mode`.

It's only suggested consistent text for discussion with the main point being to ensure any bridge is removed after flashing.

**Comment by Jason2866** [comment]
There is no `run mode`. The official modes are https://github.com/espressif/esptool/wiki/ESP8266-Boot-Mode-Selection#select-bootloader-mode

**Comment by blakadder** [comment]
> It's only suggested consistent text for discussion with the main point being to ensure any bridge is removed after flashing.

And you're making that point repeatedly

**Comment by flywire** [comment]
> There is no `run mode`. The official modes are https://github.com/espressif/esptool/wiki/ESP8266-Boot-Mode-Selection#select-bootloader-mode

Of course there is, `run` is a simpler term for `execute`. You are arguing there is no `program/flash mode` either.

> GPIO0 Input     | Mode
--------------- | ----------------------------------------------
Low/GND         | ROM serial bootloader for esptool.py
High/VCC        | Normal execution mode

Which eventually refers to [Expressif's docs](https://www.espressif.com/sites/default/files/documentation/ESP8266_Pin_List_0.xls):  `FLASH BOOT` and `UART BOOT`.

**Comment by flywire** [comment]
> And you're making that point repeatedly

I can't argue with that logic, I included it in text repeated at the end of each flashing method.

**Pull request closed without merging**
