### PR TITLE
Build features table formatting (bold headers)

### PR DESCRIPTION
**Pull request by DeflateAwning**

### CODE REVIEW

**Comment by barbudor** [comment]
This will not be merged
BUILDS.md and I2CDEVICES.md are sourced from arendst/tasmota
Place your PR there
Thanks

**Comment by DeflateAwning** [comment]
Awesome, thank you! Will do that! Did not realize that. 

It doesn't seem like the BUILDS.md file is linked or referenced anywhere in the docs repo though. That's why I proposed moving its contents to that file which lists the builds. Any thoughts on that change? 

Is the copy automatic? Just out of curiosity, where does that copy action reside? Maybe that copy action could add a markdown comment like:

```md
<!-- This file is automatically copied from https://github.com/arendst/Tasmota/blob/<applicable branch>/BUILDS.md. Please make changes upstream. -->
```

**Comment by barbudor** [comment]
As far as I know the copy is automatic when the docs are built
The doc process master is blakadder

**Comment by DeflateAwning** [comment]
@blakadder, I'm curious if the `arendst/Tasmota/BUILDS.md` file is copied to this repo (`tasmota/docs`) automatically or manually? Any thoughts?

**Comment by blakadder** [comment]
Automatically on each change

**Comment by DeflateAwning** [comment]
@blakadder Do you know where that copy is performed? 

Maybe that copy action could add a markdown comment like:

```md
<!-- This file is automatically copied from https://github.com/arendst/Tasmota/blob/<applicable branch>/BUILDS.md. Please make changes upstream. -->
```

**Pull request closed without merging**
