### PR TITLE
Update Rules.md

### PR DESCRIPTION
**Pull request by reimerp**
don't exactly know if this will trigger, but for sure Timer4 is undef. Maybe you need to create a forth one to disable rule1 at sunset. W/o this the Power stays on due to the rule during night even after Timer2

### CODE REVIEW

**Comment by ascillato** [comment]
Hi,

Thanks for your suggestions but they are not correct. Sorry.

The first one is not needed. POWER1 OFF and POWER1 0 are the same thing.

The second change is wrong. The explanation that is above the change is talking about timer1 and not timer4.

**Comment by reimerp** [comment]
Hi, 
1. I know that "Power1 OFF" and "POWER1 0" are the same, but I find it hard to understand and not a good style btw to mis both declarations in one rule. Might confuse especially newbies.

2. Timer4 should disable the rule and its missing (!). I think the intention is to
- ask the sensor during daytime
- switch on at sunset and disable the sensor
- switch off at midnightt

The current solution, does NOT deactivate the sensor, it only activates it by timer. So it stays acrive during night even it it is switched off ad midnicht by Timer. So the off time make no sense at all

**Comment by meingraham** [comment]
I agree, there is no timer #4 in write-up of the setup. It's likely a typo and should be time #1.

Recall that Rule Sets are size limited (less of an issue with compression). This is why `0` is used in rules.

If a user is advanced enough to use rules, one would hope that they have a good understanding of the commands, particularly `POWER`. In any case, if the argument is for readability and easier understanding of the example rule, then all should be made consistent. There are several instances in the Rule Cookbook of using `0`/`1`, not just the single entry you modified.

**Comment by ascillato** [comment]
> Timer4 should disable the rule and its missing

yes, you are right. It is a typo. Fixed. Thanks for reporting!!!!

**Comment by ascillato** [comment]
> I agree, there is no timer #4 in write-up of the setup. It's likely a typo and should be time #1.

yes, exactly.

**Pull request closed without merging**
