### PR TITLE
Update Displays.md

### PR DESCRIPTION
**Pull request by fb-pilot**
update links to https://tasmota.github.io/docs/Universal-Display-Driver/

### CODE REVIEW

**Comment by sfromis** [comment]
Why do you want to make those two links absolute, when the previous relative links (this format is used in all other docs links) are how it is supposed to work? Anyway, not long ago those two links were broken, I fixed them to the standard format, as used for other links.

IMO, this change should be reverted, without good reasons to do it.

**Comment by arendst** [comment]
OK. I'll revert although the links then don't work for me.

**Comment by arendst** [comment]
The reverted link ``https://tasmota.github.io/docs/Displays/Universal-Display-Driver/.md#universal-display-driver-udisplay`` doesn't work for me.

**Comment by sfromis** [comment]
Made another fix, the issue was having a slash after the page name, before the `#`. Tested to work, even if what's shown when hovering the links in a browser is what does not work in the md files.

**Comment by arendst** [comment]
Yep. Verified. Works fine now.

**Pull request merged**
