### PR TITLE
Update for adc

### PR DESCRIPTION
**Pull request by francescoadriani**
Mq on guide, image with all adc input and image for esp32;
Update for adcparam

### CODE REVIEW

**Comment by barbudor** [comment]
@francescoadriani 
Is it how it is supposed to look like ? 
Shouldn't there be a space where I highlighted in red ?
(just wondering)

image

**Comment by francescoadriani** [comment]
It is const defined on source. Could be everything on user manual. Moreover it isn't used yet! How do you prefer?

**Comment by barbudor** [comment]
OK, I was just wondering if it was what is intended.
Thanks for the collaboration

**Comment by francescoadriani** [comment]
Yes it is ppm supposed for clean air! Thanks to you to support us

**Pull request merged**
