### PR TITLE
Update Getting-Started.md

### PR DESCRIPTION
**Pull request by helgek**
Hi,

I added one paragraph as a proposal to make visitors aware of the existence of an outstanding tool called PCBite which allows flashing without soldering for those microcontrollers where there's no other option otherwise to flash.

Please consider my post in this [forum](https://github.com/syssi/esphome-yeelight-ceiling-light/discussions/72) for more details.

Best,
Helge

### CODE REVIEW

**Comment by blakadder** [comment]
No

**Comment by Jason2866** [comment]
No product placement

**Comment by helgek** [comment]
@blakadder @Jason2866 When there's only one solution on the market to provide the opportunity to many people not gifted with soldering skills to eventually flash their devices, how would you then empower them with the knowledge of this solution? I have no relationship with this company other than that I purchased their solution and successfully used it for four yeelight lamps which partly didn't work reliably (even in local network mode) and eventually through this solution I was able to flash them. Certainly the world will continue to exist also without people being able to flash some of their smarthome devices, nevermind if you don't want to add the reference.

**Comment by blakadder** [comment]
Definitely not in the Getting started documentation of an open source firmware project

**Comment by Jason2866** [comment]
There are nice alternatives. Open Source too. An example https://www.superhouse.tv/36-3d-printed-pcb-workstation-using-acupuncture-needles/

**Comment by helgek** [comment]
@Jason2866 That comes very close indeed, thanks for sharing.

**Pull request closed without merging**
