### PR TITLE
Make power numbering and button/switch control more clear

### PR DESCRIPTION
**Pull request by micw**
My 1st tasmota contribution. Feedback it's appreciated ;-)

### CODE REVIEW

**Comment by blakadder** [comment]
The assignment of buttons/switches paragraph is a very convoluted and confusing "explanation"

**Comment by ascillato** [comment]
I have added to your edit the fallback feature of switchtopic and the requirement of having switchtopic to be 0 for rules to be used.

**Comment by Jason2866** [comment]
@blakadder @ascillato  Merge now?

**Comment by ascillato** [comment]
I agree.

@Blakadder? What do you think?

**Comment by blakadder** [comment]
whatever

**Comment by micw** [comment]
@blakadder Closed without merge and without further comments?

**Comment by blakadder** [comment]
is that a rhetorical question?

**Pull request closed without merging**
