### PR TITLE
Add SetOption35 (skip number of received messages in Serial Bridge)

### PR DESCRIPTION
**Pull request by ortegafernando**
Releated with

https://github.com/arendst/Tasmota/pull/17140

https://github.com/arendst/Tasmota/commit/4f31e7a1b202268b938e9c2f2b366d847b14b68e

### CODE REVIEW

**Comment by Jason2866** [comment]
Closin since feature is not added

**Comment by ortegafernando** [comment]
Sorry, it has been added by @arendst 

Added SetOption35
And it is pending about SerialStart

If you are going to accept only when it is released, I think it is better not to close this PR, but tagging it with "pending" or something like that.
Otherwise, wikidocs will be obsolete very soon. 

Thanks.

**Comment by Jason2866** [comment]
okay

**Comment by arendst** [comment]
SO35 has indeed been implemnted some time ago.

**Comment by blakadder** [comment]
> Sorry, it has been added by @arendst
> 
> Added SetOption35 And it is pending about SerialStart
> 
> If you are going to accept only when it is released, I think it is better not to close this PR, but tagging it with "pending" or something like that. Otherwise, wikidocs will be obsolete very soon.
> 
> Thanks.

I sincerely doubt the documentation will become obsolete because of that

**Comment by ortegafernando** [comment]
Thanks, better with Wait for release. I only want to help as much as I can (not much in compare with all of you, 😜)

**Pull request merged**
