### PR TITLE
Tip regarding Domoticz/out subscribe limitations

### PR DESCRIPTION
**Pull request by soif**
Following issue [#21019](https://github.com/arendst/Tasmota/issues/21019)

### CODE REVIEW

**Comment by arendst** [comment]
Pls hold. Let me chk if I can pipe the not served domoticz topic idx to the subscribe topic action. Give me a day.

**Comment by soif** [comment]
Hi again @arendst .

As I saw your **incredibly fast commit** to support DzId for 5...32, and your nice advice to solve my case, i supposed that you were not currently willing to find a workaround to also allow subscriptions to Dz sensors... 

So to add my 2cents and to lower support to questions like mine, I wanted to contribute back by adding this note to the documentation.

I'm more than happy if it has ringed you a bell to try to enhance this particular issue, and more than impressed that , in fact, you are trying to find a simple workaround.

You guy simply ROCKS. 👍 

I owe you a beer, at least... 🍻

**Comment by soif** [comment]
_BTW, if you're using Linux/Mac OSX (Windows also works but not fuly tested/fixed), you might like to try my [Espbuddy](https://github.com/soif/EspBuddy) tool, which really eases the work when dealing / developping / coding for multiple ESP toys , and where Tasmota is certainly the most supported firmware among others...._

**Comment by arendst** [comment]
Latest change in Domoticz driver allows for disabling default subscribe by executing command ``DzIdx0 0``. This removes all defined Relay indexes and allows for user override of DOMOTICZ_OUT_TOPIC

**Pull request merged**
