### PR TITLE
Formatted Codes-for-IR-Remotes consistently as tables

### PR DESCRIPTION
**Pull request by robertoostenveld**
The page https://tasmota.github.io/docs/Codes-for-IR-Remotes/ had very inconsistent formatting for the different entries. 

In this PR I have formatted all lists and tables consistently and made some small cleanups to the headings and to the comments in each section. I have not changed any of the technical content.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
Hmm, I don't understand why there are conflicts. I thought my PR was a clean change relative to master. I will investigate...

**Comment by robertoostenveld** [comment]
> Hmm, I don't understand why there are conflicts.

It turned out that I started off from the development branch. I rebased my changes on the master branch and added the three new devices that I missed.

It is now a clean PR relative to master.

**Comment by DeflateAwning** [comment]
This would be a really good one to get merged. That page is a bit of a mess currently

**Comment by robertoostenveld** [comment]
Once it is merged, I also plan to add IR remote codes for my Samsung TV and NAD D3020 audio amplifier.

**Comment by mendel5** [comment]
I think this is a useful change, @robertoostenveld , thank you!

There is a merge conflict due to this change:
- https://github.com/tasmota/docs/pull/1292
- https://github.com/tasmota/docs/commits/master/docs/Codes-for-IR-Remotes.md

Could you maybe update your pull request to include this new change?

**Comment by robertoostenveld** [comment]
Sure, done!

**Comment by mendel5** [comment]
Thank you!

**Pull request merged**
