### PR TITLE
Create ENS161

### PR DESCRIPTION
**Pull request by chrfriese123**
ENS161 air quality sensor, follow up product for iAQcore and CCS811

### CODE REVIEW

**Comment by blakadder** [comment]
where is the code for that feature?

**Comment by chrfriese123** [comment]
Code for ENS16x and ENS210 just uploaded as pull-request

**Comment by barbudor** [comment]
PR on code has not yet been approved, so this will have to wait

**Comment by barbudor** [comment]
@chrfriese123 If you had a new pages, it should be linked from somewhere and not just happen to be here

**Comment by chrfriese123** [comment]
Thanks for feedback. I'll consider next time.

**Comment by barbudor** [comment]
I may not have been clear : Please link that page from Supported-Peripherals.md
Thanks

**Pull request merged**
