### PR TITLE
Update Zigbee.md

### PR DESCRIPTION
**Pull request by juan11perez**
Offering 3 additions for consideration:
1. Alternative flashing for the CC2530
2. Alternative hardware setup
3. Homeassistant configurations

### CODE REVIEW

**Comment by blakadder** [comment]
1. Raspberry Pi flashing is irrelevant if you already own and esp device which you have to if you want to run zigbee2tasmota
2. alternative hardware is any esp device with tx and rx pin available so no need to single out sonoff basic (which tend to have a weak power supply in some production series and will not be reliable device with CC2530 connected to it)
3. homeassistant configurations belong in Home Assistant article since not everyone uses it with Tasmota

**Comment by juan11perez** [comment]
@blakadder 
1. it's not irrelevant to inform people of an alternative flashing method that takes 5 minutes as opposed to 30. That's why i started with, if you have one. Most people doing this do have a Pi. may be not a cc debugger.
2. I mentioned the basic, because it has it's own power supply. It's an alternative.. that's all.
3. thank you for the guidance.

All in all the way you respond, does not encourage any contribution. I wrote what I wrote, because Im grateful to the programmers that built this module and give it out and since Im not a programmer it was my way of contributing. 

Im not telling anyone what to do or not. Just offering alternatives.

**Comment by blakadder** [comment]
> @blakadder
> 
> 1. it's not irrelevant to inform people of an alternative flashing method that takes 5 minutes as opposed to 30. That's why i started with, if you have one. Most people doing this do have a Pi. may be not a cc debugger.

write a tutorial about flashing a cc2530 using a nodemcu/wemos.. most people don't have a raspberry pi, myself included.

> 2. I mentioned the basic, because it has it's own power supply. It's an alternative.. that's all.
> 3. thank you for the guidance.
> 
> All in all the way you respond, does not encourage any contribution. I wrote what I wrote, because Im grateful to the programmers that built this module and give it out and since Im not a programmer it was my way of contributing.
>
>
> Im not telling anyone what to do or not. Just offering alternatives.

same here and i offered constructive criticism. there's a difference between information and pertinent information

**Comment by Jason2866** [comment]
@juan11perez   i would be happy if you write a article about the altenative flashing methode
with a NodeMCU using CCLoader https://github.com/Jason2866/CCLoader 
This flashing method is reliable and fast and done under 3 minutes.
Since Zigbee2Tasmota needs a ESP device to work everyone has the needed

**Comment by juan11perez** [comment]
@Jason2866  
hi Jason, so I tried flashing with a wemos d1. This is what I did:
flashed the wemos with your [CCLoader.ino](https://github.com/Jason2866/CCLoader/blob/master/CCLoader/src/CCLoader.ino)
downloaded your [.exe](https://github.com/Jason2866/CCLoader/blob/master/Windows/CCLoader_x86_64.exe)
connected the pins per your diagram; finding the corresponding using this [CC2530 pins](http://www.marrold.co.uk/2019/12/flashing-cc2530-cc2591-zigbee-module.html)

Open windows powershell, typed 
CCLoader_x86_64.exe 4 CC2530ZNP-Prod.bin 0

Loader starts, but i get no response from "Arduino".

Am I missing something in the process?

**Comment by blakadder** [comment]
I wrote a more detailed guide yesterday https://zigbee.blakadder.com/flashing_ccloader.html, still missing some images to make it clearer

**Comment by juan11perez** [comment]
@blakadder  the link says 
404
Page not found :(

**Comment by Jason2866** [comment]
@juan11perez  Thx, for looking into. You can download the [CCLoader.bin](https://github.com/Jason2866/CCLoader/blob/master/Bin/CCLoader_Arduino.bin)
and flash it direct to the ESP. No need to compile yourself.
In the source code there is the used GPIO pin config (how to wire) documented too https://github.com/Jason2866/CCLoader/blob/master/CCLoader/src/CCLoader.ino#L86

**Comment by blakadder** [comment]
> @blakadder the link says
> 404
> Page not found :(

should work now

**Comment by Jason2866** [comment]
Thx @blakadder  Just linked your nice explanation

**Pull request closed without merging**
