### PR TITLE
Update Blinds-and-Shutters.md

### PR DESCRIPTION
**Pull request by lordjaxom**
add example for OpenHAB2 rollershutter MQTT channel configuration

### CODE REVIEW

**Comment by meingraham** [comment]
I would recommend putting this openHAB information in a separate article and then linking to it from the Blinds & Shutters article as well as the openHAB integration article.

**Comment by lordjaxom** [comment]
Do you have any idea on where to put the separate article?

**Comment by meingraham** [comment]
Same folder, just a new .md file

**Comment by Jason2866** [comment]
@lordjaxom  do you finde some time to add this to the OpenHab section 
https://tasmota.github.io/docs/#/integrations/openHAB

**Comment by stefanbode** [comment]
I see that the transformation map is not required anymore. Instead of sending it to backlog you can send directly to shutterposition1. This now also understand UP/DOWN/STOP and for sure the 0..100.

**Comment by lordjaxom** [comment]
Thanks for pointing that out. I am hereby closing my pull request.

**Pull request closed without merging**
