### PR TITLE
Include the GUI display name where it differs

### PR DESCRIPTION
**Pull request by sillyfrog**
This is something I needed when searching for what `Switch_n` is in the GUI. Happy to lay it out in a different way (eg: a dedicated column, or anything else you suggest).

The goal is to have it so the name displayed in the GUI is searchable in the docs (which it currently isn't).

### CODE REVIEW

**Comment by blakadder** [comment]
why not use the GUI name as it is shown?

**Comment by sillyfrog** [comment]
To clarify, in the GUI, it has the option as `Switch_n` (see below) - I wanted to search for this in the docs to find out what it means. In the docs, for example, it has `Switch1n`. So when I entered `Switch_n`, I got not results. I was trying to come up with a way to make it more discoverable (hopefully that makes sense?) - happy with any other ideas :) 

Cheers.

image

**Comment by blakadder** [comment]
Change the `Switch1n` to `Switch_n 1` and so forths... The former is pre 9 nomenclature while the latter is used now

**Comment by sillyfrog** [comment]
How's that look?

**Comment by blakadder** [comment]
almost perfect

**Pull request merged**
