### PR TITLE
Update Buttons-and-Switches.md

### PR DESCRIPTION
**Pull request by bennydente**

### CODE REVIEW

**Comment by blakadder** [comment]
That warning is unneccessary since you **are** creating a rule to send to a topic which automatically ignores SwitchTopic 0. That is there just to return SwitchTopic to default state so the rule will 100% work

**Comment by bennydente** [comment]
Maybe I did not say it clear enough. I try to explain myself better.

As described in the document:
"SwitchTopic 0 doesn't send any MQTT messages itself. No MQTT message will be published on account of the new switch state."

But if I set the Rule to avoid Power control, the system writes the topic as set in the Rule, but it also write a topic as if the SwitchTopic 1 directive is enabled.

**Comment by blakadder** [comment]
default
```
11:45:01 MQT: stat/tx3switch/RESULT = {"SwitchMode1":0}
11:45:12 MQT: stat/tx3switch/RESULT = {"POWER1":"OFF"}
11:45:12 MQT: stat/tx3switch/POWER1 = OFF
11:45:12 MQT: stat/tx3switch/RESULT = {"POWER1":"ON"}
11:45:12 MQT: stat/tx3switch/POWER1 = ON
```
switchtopic 1 using default topic
```
11:45:34 CMD: switchtopic 1
11:45:34 MQT: stat/tx3switch/RESULT = {"SwitchTopic":"tx3switch"}
11:45:45 MQT: cmnd/tx3switch/POWER1 = OFF
11:45:45 MQT: stat/tx3switch/RESULT = {"POWER1":"OFF"}
11:45:45 MQT: stat/tx3switch/POWER1 = OFF
11:45:45 MQT: cmnd/tx3switch/POWER1 = ON
11:45:45 MQT: stat/tx3switch/RESULT = {"POWER1":"ON"}
11:45:45 MQT: stat/tx3switch/POWER1 = ON
```
rule enabled:
```
11:46:32 CMD: Backlog SwitchMode 1; SwitchTopic 0
11:46:32 MQT: stat/tx3switch/RESULT = {"SwitchMode1":1}
11:46:32 MQT: stat/tx3switch/RESULT = {"SwitchTopic":""}
11:46:51 CMD: Backlog Rule1 on Switch1#state do Publish cmnd/rule-only-topic/SWITCH %value% endon; Rule1 1
11:46:51 MQT: stat/tx3switch/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Free":442,"Rules":"on Switch1#state do Publish cmnd/rule-only-topic/SWITCH %value% endon"}
11:46:51 MQT: stat/tx3switch/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":442,"Rules":"on Switch1#state do Publish cmnd/rule-only-topic/SWITCH %value% endon"}
11:46:59 RUL: SWITCH1#STATE performs "Publish cmnd/rule-only-topic/SWITCH 0"
11:46:59 MQT: cmnd/rule-only-topic/SWITCH = 0
11:46:59 RUL: SWITCH1#STATE performs "Publish cmnd/rule-only-topic/SWITCH 1"
11:46:59 MQT: cmnd/rule-only-topic/SWITCH = 1
```
can you tell me where exactly is the point where switchtopic 0 is ignored?

arendst/Tasmota#8178

**Comment by bennydente** [comment]
In my scenario i have this:
trying on sonoff basic.

(Rule1 is disabled):
`12:11:23 CMD: SwitchMode1
12:11:23 MQT: testsonoff01/stat/RESULT = {"SwitchMode1":1}
12:11:25 CMD: switchtopic
12:11:25 MQT: testsonoff01/stat/RESULT = {"SwitchTopic":""}
12:11:37 CMD: Rule1
12:11:37 MQT: testsonoff01/stat/RESULT = {"Rule1":"OFF","Once":"OFF","StopOnError":"OFF","Free":444,"Rules":"on Switch1#state do Publish %topic%/stat/SWITCH1_STAT %value% endon"}
`

When close/open switch1 i have:
`12:14:07 MQT: testsonoff01/stat/SWITCH1 = {"STATE":"OFF"}
12:14:07 MQT: testsonoff01/tele/STATE = {"Time":"2020-04-15T12:14:07","Uptime":"0T01:10:35","UptimeSec":4235,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"OFF","Wifi":{"AP":1,"SSId":"B3_AUTH_ONLY","BSSId":"EC:08:6B:42:65:9F","Channel":11,"RSSI":78,"Signal":-61,"LinkCount":1,"Downtime":"0T00:00:06"}}
12:14:07 MQT: testsonoff01/stat/RESULT = {"POWER":"OFF"}
12:14:07 MQT: testsonoff01/stat/POWER = OFF
12:14:09 MQT: testsonoff01/stat/SWITCH1 = {"STATE":"ON"}
12:14:09 MQT: testsonoff01/tele/STATE = {"Time":"2020-04-15T12:14:09","Uptime":"0T01:10:37","UptimeSec":4237,"Heap":25,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"POWER":"ON","Wifi":{"AP":1,"SSId":"B3_AUTH_ONLY","BSSId":"EC:08:6B:42:65:9F","Channel":11,"RSSI":76,"Signal":-62,"LinkCount":1,"Downtime":"0T00:00:06"}}
12:14:09 MQT: testsonoff01/stat/RESULT = {"POWER":"ON"}
12:14:09 MQT: testsonoff01/stat/POWER = ON`

If I enable Rule1
`12:24:10 CMD: rule1 1
12:24:10 MQT: testsonoff01/stat/RESULT = {"Rule1":"ON","Once":"OFF","StopOnError":"OFF","Free":444,"Rules":"on Switch1#state do Publish %topic%/stat/SWITCH1_STAT %value% endon"}
12:24:19 RUL: SWITCH1#STATE performs "Publish testsonoff01/stat/SWITCH1_STAT 0"
12:24:19 MQT: testsonoff01/stat/SWITCH1_STAT = 0
12:24:19 MQT: testsonoff01/stat/SWITCH1 = {"STATE":"OFF"}
12:24:21 RUL: SWITCH1#STATE performs "Publish testsonoff01/stat/SWITCH1_STAT 1"
12:24:21 MQT: testsonoff01/stat/SWITCH1_STAT = 1
12:24:21 MQT: testsonoff01/stat/SWITCH1 = {"STATE":"ON"}`

Why MQT: testsonoff01/stat/SWITCH1 = {"STATE":"ON"} or MQT: testsonoff01/stat/SWITCH1 = {"STATE":"OFF"} if Switchtopic 0 is set?

**Comment by effelle** [comment]
> Why MQT: testsonoff01/stat/SWITCH1 = {"STATE":"ON"} or MQT: testsonoff01/stat/SWITCH1 = {"STATE":"OFF"} if Switchtopic 0 is set?

Because you are mixing thing. You have enabled the HA discovery. More info [here](https://tasmota.github.io/docs/Home-Assistant/#automatic-discovery)

**Comment by bennydente** [comment]
oook. Right, this is the reason. thanks a lot.

**Pull request closed without merging**
