### PR TITLE
Erase flash memory

### PR DESCRIPTION
**Pull request by flywire**
Device does not need to power cycle when erasing flash memory with esptool.py or it's derivatives while flashing

### CODE REVIEW

**Comment by flywire** [comment]
Note for `esptool.py` and `esptool executable` can erase memory on same command line as flashing. Both versions use exactly the same commands which should be listed once.

**Comment by blakadder** [comment]
its always recommended to power cycle after erasing flash

**Comment by flywire** [comment]
That's old advice: https://github.com/espressif/esptool/releases/tag/v2.6 and not compatible with Tasmotizer

**Comment by blakadder** [comment]
Then change the esptool.py section not general advice.

What do you mean not compatible with Tasmotizer?

**Comment by flywire** [comment]
Erasing flash can be essential before flashing but the main point is it doesn't _require_ power cycling.

I assumed Tasmotizer was running esptool.py code so the same comments would apply, especially given the following. Tasmotizer has a tick box to `Erase before flashing` but it seems Tasmotizer must flash when it runs (ie can't erase without flashing).

**Pull request closed without merging**
