### PR TITLE
Replace "f.e." with "e.g.,"

### PR DESCRIPTION
**Pull request by DeflateAwning**
"e.g." is the correct abbreviation of "for example" in English

### CODE REVIEW

**Comment by mendel5** [comment]
I think this is a useful change and would appreciate it if somebody could merge this pull request.

**Review by stefanbode — APPROVED** [review]

**Comment by barbudor** [comment]
It doesn't build
There seems to be wrong link to pictures
Probably not your fault but it would be great to fix it before the merge

**Comment by DeflateAwning** [comment]
Thanks for checking it over and merging. I just branched off of master, so that's likely where the issues came from

**Comment by mendel5** [comment]
Thank you!

**Pull request merged**
