### PR TITLE
Update Timezone-Table.md

### PR DESCRIPTION
**Pull request by MorganBlack**
Corrected settings of the DST/STD for Europe/Dublin zone.

### CODE REVIEW

**Comment by barbudor** [comment]
@MorganBlack timezone table shouldn't be updated manually as it is supposed to be auto-generated

@cpfair could you please kindly look why Europe/Berlin is wrong
Thanks

**Comment by cpfair** [comment]
I believe this was a bug in the generation script and was fixed in #1108 - unfortunately that PR has not been merged yet.

**Comment by blakadder** [comment]
It is currently in conflict with existing code so it's quite difficult to merge

**Comment by cpfair** [comment]
@blakadder which conflicts are you seeing? I was able to do the merge locally without issue. In any case, I have rebased #1108's branch onto the current tip of master (1bf4f8d97381b88103529830e468c279d0cdb886) so hopefully that resolves any merge issues.

**Comment by MorganBlack** [comment]
Hi,
Sorry I wasn't aware that the Timezone table was generated automatically. 
Also, it's my first pull request.
Closing.
Thank you.

**Pull request closed without merging**
