### PR TITLE
Update Zigbee.md

### PR DESCRIPTION
**Pull request by jeroenst**
Added rule for sending zigbee sensor data into own topics

### CODE REVIEW

**Comment by nagyrobi** [comment]
This is great to know!

**Comment by barbudor** [comment]
@jeroenst 
Could you kindly fix those typos:
"to there own MQTT " => "to thir own MQTT "
"folowing" => "following"
"preffered" => "preferred" 
Should be faster if you do it in your fork
Thanks

**Comment by barbudor** [comment]
@jeroenst Any chance you can fix the typos listed above ?

**Comment by jeroenst** [comment]
Ok I did the requested changes, sorry it took so long.

**Pull request merged**
