### PR TITLE
Update PIR-Motion-Sensors.md

### PR DESCRIPTION
**Pull request by FloatingBoater**
Added specifications of the HC-SR501 and AM312, and experience using the AM312 with a Sonoff Dual R2.

### CODE REVIEW

**Comment by blakadder** [comment]
too technical for the scope of the article

**Comment by FloatingBoater** [comment]
> too technical for the scope of the article

Shame.
As it stands, the article is misleading, as available AM312 devices don't work with ESP GPIOs.

**Comment by blakadder** [comment]
don't work in what way?

**Comment by Jason2866** [comment]
Strang why does it work for me since 2 years?

**Comment by FloatingBoater** [comment]
Hi,

The details are in the rejected update to the docs, but in summary, either a recent batch of 'clone' AM312 has a too high output decoupling resistor (20kR), or a Sonoff Dual R2 Button1 / GPIO09 has too low a pull-up resistor, as directly connecting them as standard doesn't trigger the pin low. 

A DVM confirms the voltage swing is too low for the ESP to see.

The HC-SR501 triggers the pin, but as it's designed for 5V and not 3V3, it false triggers like crazy.

My docs update was intended to help others not hit this problem, and give a fix. I've not (yet) tested with different like, like a bare board ESP12F or Wemos clone.

TTFN,

James

**Pull request closed without merging**
