### PR TITLE
Create Shutter-and-Steppers.md

### PR DESCRIPTION
**Pull request by TrDA-hab**
first commit

### CODE REVIEW

**Comment by meingraham** [comment]
I will review & edit over the weekend so we can merge this content into the main Shutter article.

**Comment by stefanbode** [comment]
All fine. Documentation is ok and works.

**Comment by TrDA-hab** [comment]
@meingraham 
1. All restrictions in my NOTE 0 ... 2 are **only** software limitations. Detailed information is available **only from the author - stefanbode**. I can’t explain it well. If I correctly understood the information from Stefan, then the "problem" is the simultaneous use of several PWM.

2. How to configure stepper drivers? - please see, I gave links - "5. For configure your stepper drivers use tutorials: A4988 or DRV8825 or TMC2208".

3. Use the **same combination** of stepper drivers and stepper motor (examples):
 - good configuration: Shutter#1=(A4899#1 + Nema17#1) **equals** Shutter#2=(A4899#2 + Nema17#2). Easy setup and stable operation.
 - poor configuration: Shutter#1=(DRV8825#1 + Nema8#1) **unequal** Shutter#2=(TMC2208#2 + Nema34#2). Very complicated setup and possible operation problems.

4. Bill of materials - I do it without problems. This is a good idea.

**Comment by ceraz68** [comment]
The bill of materials is really useful but the diagrams refer to 100mF 35V or 50V capacitors but the bill of materials refers to 100uF or 10uF aliexpress webpages.

Is there a mistake in the diagram (replace mF by uF) ? and then in the bill of materials replace the 35V 10uF capacitor by 50V 100uF ?

**Comment by TrDA-hab** [comment]
> (replace mF by uF) ?

mF = uF 
https://www.wikihow.com/Read-a-Capacitor

**Comment by ceraz68** [comment]
Hi @TrDA-hab as the page says:

> (Careful — in other contexts, mF is the official abbreviation for millifarads, or 10-3 farads.)

I read milli, so got tripped!

If the second capacitor pointed to 100uF 50V it might help.

Thanks for all your work on these pages 👍

**Pull request merged**
