### PR TITLE
Update DS18x20 docs

### PR DESCRIPTION
**Pull request by krystof-k**
I updated the docs with regards to the recent DS18x20 enhancements  introduced in arendst/Tasmota#16649 and arendst/Tasmota#16833, ready for the v12.3 release.

### CODE REVIEW

**Comment by krystof-k** [comment]
@md5sum-as, I would be happy if you can check it :)

**Comment by md5sum-as** [comment]
Hello.
Everything is right.
Should we specify that when n=0 (in the DS18 command Alias \<sensor id\>,\<n\>) the alias will be deleted and the default schema will be returned?

**Comment by krystof-k** [comment]
Sure! Added.

**Comment by blakadder** [comment]
thanks

**Pull request merged**
