### PR TITLE
Spelling and grammar fixes

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by barbudor** [comment]
Hi @scop 
This is a huge work
May I kindly ask if you've done that manually or used a tool ?

I think it may be too large to be validated as a single PR, especially the quantity of changes in Commands.md is very large.
@blakadder Do you think this should be splitted into multiple PR ? May be 10 files no more ? And a oen especially for Commands.md ?

**Comment by scop** [comment]
Most fixes are by https://github.com/crate-ci/typos, some with a local simple "a vs an" checker tool.

**Comment by barbudor** [comment]
Could be interresting to add that to the CI of docs. Would be great if it could automatically create PR reviews 🤣 
@blakadder what do you think of it ?

**Comment by blakadder** [comment]
I'm down with it. Also fine with this being single PR just need to skim through the changes

**Comment by blakadder** [comment]
Definitely the best PR ever on this GitHub!

**Pull request merged**
