### PR TITLE
Add documentation for BLE stuff relating to BLE_ESP32

### PR DESCRIPTION
**Pull request by btsimonh**
Long awaited, should help with some of the questions.
There is probably more that could be added, but this is the basics for the moment.
Also splits the ESP32 stuff away from the use of external modules; keeps the docs cleaner.
I have added an EQ3 doc - this is for those building from my branch; it's still not stable, so not ready for a PR; but it's quietly linked off the bottom.  (we had at least one other dev who started an EQ3 driver.... so want something in there to indicate how and where they can contribute...).

### CODE REVIEW

**Comment by btsimonh** [comment]
HOLD.
there ia gh-pages publishing issue with a directory case thing.  I'm changing my subfolder form bluetooth to ble to avoid it.
Expect a push....  will signal when ready.

**Comment by btsimonh** [comment]
ok, ready again.  The change just avoids a case issue in folder naming.

**Comment by blakadder** [comment]
why the subfolder for docs?

**Comment by btsimonh** [comment]
I saw the subfolders for devices, installation, and thought it appropriate to keep things together.  Should make it easier to manage.
Is there a down-side to a subfolder (except if, like me, you initially named it the same as an existing or replaced .md file!).


hmmm... why does it now have conflicts?

**Comment by blakadder** [comment]
because you were changing filenames willynilly... please keep everything in Bluetooth.md as it was

**Comment by btsimonh** [comment]
docs/Bluetooth.md should be deleted - it's been split into two for clarity; one dedicated to external BLE, and one dedicated to  internal ESP32 BLE.
you can see the desired result here:

https://btsimonh.github.io/docs/Features/

**Comment by btsimonh** [comment]
ahhh... shit, sorry.  let me properly redo this.
My branch was based off @barbudor 's development branch.  That's why there are conflicts.
br, Simon
Can I keep my subfolder? please.....

**Comment by btsimonh** [comment]
New PR in.

**Pull request closed without merging**
