### PR TITLE
Update to describe SetOption147

### PR DESCRIPTION
**Pull request by ortegafernando**
Describe SetOption147.

As this PR (https://github.com/arendst/Tasmota/pull/16612) has been approved, I must update also the wiki.

I have added lines for 145 and 146 but I don't know preciselly what they do.

I have also added one paragraph above Serial Bridge description

### CODE REVIEW

**Comment by barbudor** [comment]
I have added the details for SO145 and SO146
Thanks for the contribution

**Comment by barbudor** [comment]
Sorry but the PR should be against development, not master
docs/master should match tasmota/master and
docs/development shouls match tasmota/development

Could you please redo it against development (and keep my changes on SO145 and SO146) ?

thanks

**Comment by ortegafernando** [comment]
@barbudor Just to ensure.... in master I can see that it is described until SetOption144. In developement branch, until SetOption135

I think that I need to make the PR against master, don't I?

Thanks

**Comment by barbudor** [comment]
No, you PR in Tasmota got into the dev branch, so your PR on doc should do the same.
If docs master stops at so144 it's most probably because so145 is not yet in release but in dev.

Just insure your text for so144 is the as in master

**Comment by ortegafernando** [comment]
> No, you PR in Tasmota got into the dev branch, so your PR on doc should do the same. If docs master stops at so144 it's most probably because so145 is not yet in release but in dev.
> 
> Just insure your text for so144 is the as in master

I think that I have not explained well.

If i make the PR to developement branch, it will only have from setoption 1 to 135 and then setoption 145, 146 and 147.
If i make the PR to master branch, it will only have from setoption 1 to 144 and then setoption 145, 146 and 147.

Repository (developements) says: "This branch is [7 commits ahead](https://github.com/tasmota/docs/compare/master...development), [347 commits behind](https://github.com/tasmota/docs/compare/development...master) master."

Two screenshots: developement first and then master.
d1
t1

I will do the PR to what you say, but I understand that I need only to update from 145 to 147 or from 136 to 147??? It is strange for me, I am not an expert in github. It seems that master is more new than developement.

Please, confirm

**Comment by barbudor** [comment]
I confirm that the docs/master repository shoudl not include any feature that are not in tasmota/master

Your setoption147 feature in in tasmota/development so please make your doc PR in docs/development

Forget about so145/so146 we will deal with it, just do your so147 in docs/development

Thanks you

**Pull request closed without merging**
